# Generated by Django 4.0.8 on 2022-11-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vsmatt',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/vsmatt/logo'),
        ),
    ]
