# Generated by Django 4.0.8 on 2022-10-30 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesscategory',
            options={'ordering': ('title',), 'verbose_name': 'category', 'verbose_name_plural': 'Business Categories'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ('title',), 'verbose_name': 'category', 'verbose_name_plural': 'Product Categories'},
        ),
    ]
