# Generated by Django 4.0.8 on 2022-10-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jujamall',
            name='latitude',
            field=models.DecimalField(decimal_places=16, default=-1.1139084362152138, max_digits=22),
        ),
        migrations.AddField(
            model_name='jujamall',
            name='longitude',
            field=models.DecimalField(decimal_places=16, default=37.0106327842076, max_digits=22),
        ),
    ]
