# Generated by Django 4.0.8 on 2022-10-30 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_jujamall_latitude_jujamall_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='marker',
        ),
    ]
