# Generated by Django 4.0.8 on 2022-10-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_team_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimony',
            name='title',
        ),
        migrations.AlterField(
            model_name='team',
            name='photo',
            field=models.ImageField(upload_to='team/'),
        ),
    ]
