# Generated by Django 4.0.8 on 2022-10-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_jujamall'),
    ]

    operations = [
        migrations.AddField(
            model_name='jujamall',
            name='set_current',
            field=models.BooleanField(default=False),
        ),
    ]
