# Generated by Django 4.0.8 on 2022-10-26 09:11

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_jujamall_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='photo',
            field=models.ImageField(upload_to=core.models.content_file_name),
        ),
    ]
