# Generated by Django 4.0.7 on 2022-10-22 23:36

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessbranch',
            name='marker',
            field=models.ImageField(default='hellow', upload_to=core.models.markers_file_name),
            preserve_default=False,
        ),
    ]
