# Generated by Django 4.0.8 on 2022-10-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessbranch',
            name='address',
            field=models.CharField(default='juja jkuat', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='address',
            field=models.CharField(max_length=300),
        ),
    ]
