# Generated by Django 4.0.8 on 2022-10-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_businessbranch_address_alter_businessprofile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessbranch',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='businessbranch',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
