# Generated by Django 4.0.8 on 2022-10-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_businessbranch_marker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessbranch',
            name='address',
        ),
        migrations.RemoveField(
            model_name='businessbranch',
            name='geolocation',
        ),
        migrations.AddField(
            model_name='businessbranch',
            name='latitude',
            field=models.DecimalField(decimal_places=16, default=-1.1139084362152138, max_digits=22),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessbranch',
            name='longitude',
            field=models.DecimalField(decimal_places=16, default=37.0106327842076, max_digits=22),
            preserve_default=False,
        ),
    ]
