# Generated by Django 4.0.8 on 2022-10-30 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_productcategory_marker'),
        ('shop', '0002_businessbranch_address_alter_businessprofile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessbranch',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='core.businesscategory'),
        ),
    ]
