# Generated by Django 4.0.8 on 2022-10-30 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_businessbranch_category'),
        ('shop', '0004_businessprofile_is_approved_and_more'),
    ]

    operations = [
    ]
