# Generated by Django 4.0.8 on 2022-11-04 14:35

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_branchreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessbranch',
            name='customer_service_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
